install:
 # ActivePerl
 - cinst activeperl
 - perl -V

 # Strawberry
 - cinst strawberryperl
 - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
 - perl -V

 - cd C:\projects\p5-Git-Raw

 - git config --global user.name "p5-Git-Raw"
 - git config --global user.email "jacquesg@cpan.org"

 - cpanm --notest Dist::Zilla Dist::Zilla::PluginBundle::Author::ALEXBIO Pod::Coverage::TrustPod
 - cpanm --quiet --notest Devel::Cover::Report::Coveralls Dist::Zilla::App::Command::cover
 - dzil authordeps --missing | cpanm --notest
 - dzil listdeps --missing | cpanm --notest

build_script:
 - dzil test --all
